#!/bin/bash

cd /sys/kernel/config/usb_gadget/

mkdir -p piusb
cd piusb

# Set some config info
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0x0008 > bDeviceClass # Class of USB device

# Set strings
mkdir -p strings/0x409
echo "fe802c93c36e4eae7e09" > strings/0x409/serialnumber
echo "Richard Wells" > strings/0x409/manufacturer
echo "Raspberry Pi USB Emulator" > strings/0x409/product

# Set max power
mkdir -p configs/c.1/strings/0x409
echo 250 > configs/c.1/MaxPower

# Specify which disk image to use for mass storage
FILE=/home/pi/piusb/storage/ramdisk/fs.img

# Set gadget options
mkdir -p functions/mass_storage.usb0
echo 1 > functions/mass_storage.usb0/stall
echo 0 > functions/mass_storage.usb0/lun.0/cdrom
echo 1 > functions/mass_storage.usb0/lun.0/removable
echo 0 > functions/mass_storage.usb0/lun.0/ro
echo 0 > functions/mass_storage.usb0/lun.0/nofua
echo "Richard Drive" > functions/mass_storage.usb0/lun.0/inquiry_string
echo $FILE > functions/mass_storage.usb0/lun.0/file
ln -s functions/mass_storage.usb0 configs/c.1/

# Enable the gadget in the UDC
ls /sys/class/udc > UDC
