#!/bin/bash
cd /sys/kernel/config/usb_gadget/

mkdir -p piusb
cd piusb
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0x0008 > bDeviceClass # Class of USB device

mkdir -p strings/0x409
echo "fe802c93c36e4eae7e09" > strings/0x409/serialnumber
echo "Richard Wells" > strings/0x409/manufacturer
echo "Raspberry Pi USB Emulator" > strings/0x409/product

mkdir -p configs/c.1/strings/0x409
echo 250 > configs/c.1/MaxPower

# Add functions here

FILE=/home/pi/fs.img
#mkdir -p ${FILE/img/d}

#mount -o loop -t vfat $FILE ${FILE/img/d}

mkdir -p functions/mass_storage.usb0
echo 1 > functions/mass_storage.usb0/stall
echo 0 > functions/mass_storage.usb0/lun.0/cdrom
echo 1 > functions/mass_storage.usb0/lun.0/removable
echo 0 > functions/mass_storage.usb0/lun.0/ro
echo 0 > functions/mass_storage.usb0/lun.0/nofua
echo "Richard Drive" > functions/mass_storage.usb0/lun.0/inquiry_string
echo $FILE > functions/mass_storage.usb0/lun.0/file
ln -s functions/mass_storage.usb0 configs/c.1/

# End functions

ls /sys/class/udc > UDC
