#!/bin/bash

# Start the TP
tpm2_startup -c

# Specify the password used to access the key
password=$1

# Get the AES key from the TPM
aeskey=$(echo $(/home/pi/piusb/encryption/unseal_key $password) | awk '{print $NF}')

#DEBUG
echo "AES KEY:"
echo $aeskey

# Encrypt the file using this AES key
echo ""
echo "- File encrypted:"
openssl enc -nosalt -aes-256-cbc -in /home/pi/piusb/storage/ramdisk/fs.img -out /home/pi/piusb/storage/images/fs.img.encrypted -k $aeskey