#!/bin/bash

# Start the TPM
tpm2_startup -c

# Flush transient objects to save memory
tpm2_flushcontext -t


#Address of key to encrypt data
keyaddress=$1

# Data to be encrypted asymmetrically
plaintext=$2

# Encrypt the data, using the public key stored in the specified persistent address in the TPM
tpm2_rsaencrypt -c $keyaddress $plaintext