#!/bin/bash

# Start the TPM
tpm2_startup -c

# Flush transient objects to save memory
tpm2_flushcontext -t


#Address of key to decrypt data
keyaddress=$1

# Data to be decrypted asymmetrically
ciphertext=$2

# Decrypt the data, using the private key stored in the specified persistent address in the TPM
tpm2_rsadecrypt -c $keyaddress $ciphertext