#!/bin/bash

# Start the TPM
tpm2_startup -c

# Specify the AES key used to encrypt the files
aeskey=$1

# Decrypt the file using this AES key
echo ""
echo "# File decrypted:"
openssl enc -nosalt -aes-256-cbc -md sha512 -pbkdf2 -d -in ./storage/images/fs.img.encrypted -out ./storage/ramdisk/fs.img -k $aeskey