#!/bin/bash

# Start the TPM
tpm2_startup -c

# Specify the password used to access the key
password=$1

# Get the AES key from the TPM
aeskey=$(echo $(./encryption/scripts/unseal_key $password) | awk '{print $NF}')

#DEBUG
echo $aeskey

# Decrypt the file using this AES key
echo ""
echo "- File decrypted:"
openssl enc -nosalt -aes-256-cbc -d -in ./storage/images/fs.img.encrypted -out ./storage/ramdisk/fs.img -k $aeskey