#!/bin/bash

# Start the TPM
tpm2_startup -c

# Specify the passcode used to access the key
passcode=$1

# Get the AES key from the TPM
aeskey=$(echo $(./encryption/scripts/unseal_key $passcode) | awk '{print $NF}')

echo "- AES KEY:"
echo $aeskey

# Decrypt the file using this AES key
echo ""
echo "- File decrypted:"
openssl enc -nosalt -aes-256-cbc -md sha512 -pbkdf2 -d -in ./storage/images/fs.img.encrypted -out ./storage/ramdisk/fs.img -k $aeskey