#!/bin/bash

# Start the TPM
tpm2_startup -c

# Specify the AES key used to encrypt the files
aeskey=$1

# Encrypt the file using this AES key
echo ""
echo "# File encrypted:"
openssl enc -nosalt -aes-256-cbc -md sha512 -pbkdf2 -in ./storage/ramdisk/fs.img -out ./storage/images/fs.img.encrypted -k $aeskey