#!/bin/bash

# Start the TPM
tpm2_startup -c

# Specify the passcode used to access the key
passcode=$1

# Get the AES key from the TPM
aeskey=$(echo $(./encryption/scripts/unseal_key $passcode) | awk '{print $NF}')

#DEBUG
echo "AES KEY:"
echo $aeskey

# Encrypt the file using this AES key
echo ""
echo "- File encrypted:"
openssl enc -nosalt -aes-256-cbc -md sha512 -pbkdf2 -in ./storage/ramdisk/fs.img -out ./storage/images/fs.img.encrypted -k $aeskey