#!/bin/bash

echo $1
echo $2

# Write the file system image to the ramdisk folder
dd bs=$1 count=$2 if=/dev/zero of=./storage/ramdisk/fs.img

# Format the backing file as FAT
mkfs.exfat ./storage/ramdisk/fs.img